[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = api/v1/users/tests api/v1/tasks/tests api/v1/auth/tests tasks/tests users/tests
pythonpath = .
addopts = --import-mode=importlib