"""initial users and tasks

Revision ID: 31070ae2629d
Revises: 
Create Date: 2026-07-29 04:36:04.620995

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '31070ae2629d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
